### ISSUE TITLE
Week 2: Yelp

### ISSUE THREAD

**Issue by ananavati** [ananavati/codepath_yelp#1]
Assignment submission
@timothy1ee @nesquena

definitely needs some clean up on filter settings, right now i am passing in values as Dictionaries but a model to save that state and settings will be much more cleaner.

**Comment by timothy1ee** [comment]
Arpan,

You should be aiming for a higher level of polish. Your images are squashed, your layout is not good.
- In your nibs, all subviews should have constraints.
- Your filter view is missing an expandable section, please add that and let me know when it's done.
- "Sort by" is a radio concept, but you've allowed it to be multi-select.
- You're calling an optional method on your delegate without checking to see if it can perform that selector which may cause a crash.

These details matter, and you'll find that it's often technically non-trivial to reach a high level of polish that quality iOS applications have.

The purpose of this assignment was to explore the following:
- Table views with dynamic height rows and custom cells with Auto Layout.
- Table views that contain controls for user input and binding those controls to form data.
- Advanced features of table views such as row animation and section views.
- Linking two view controllers view a custom delegate pattern.

Here's my checklist as I'm reviewing the submissions:
- Code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you should take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
- Custom cells.
  - Are the subviews of the cell exposed in the public header or are they properly encapsulated?
  - Do the nibs have the proper Auto Layout constraints?
  - Are the cells registered with the table view?
- Filter view controller
  - Are the controls properly bound with the form data?
  - Is there a custom delegate to notify the search view controller of new filter settings?
  - Is there a section in the table view that accordians out?

**Comment by ananavati** [comment]
Thanks for the review/comments, yep I agree this code is pretty embarrassing.
